version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "install step"
      - npm install -g serverless
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "build command"
  post_build:
    commands:
      - echo "post_build step"