service: kinesisFinder

provider:
  name: aws
  region: ca-central-1
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudformation:ListStacks
        - kinesis:ListStreams
        - ec2:DescribeRegions
      Resource: '*'
functions:
  kinesisFinder:
    handler: index.handler
    runtime: nodejs8.10
    events:
      - schedule: cron(20 19 ? * FRI *)